# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171019_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bank_account',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
